---
name: Alexa Skill
guid: c5df7de0-8777-4b3c-a70d-5c3dae359c9e
version: 0.1.0.1
targetAbi: 10.10.7
framework: net8.0
overview: Alexa skill plugin for Jellyfin
description: >
  This is a Jellyfin plugin for an Alexa skill to play media from your Jellyfin server.
  Besides, simple playback, other additional functions like playback of playlists or managing favorites are included.
category: General
owner: "paolo"
artifacts:
  - Alexa.NET.dll
  - Alexa.NET.Management.dll
  - Amazon.Lambda.Core.dll
  - Amazon.Lambda.Serialization.Json.dll
  - Jellyfin.Plugin.AlexaSkill.dll
  - Refit.dll
changelog: ""
