using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Runtime.InteropServices;
using System.Threading;
using System.Threading.Tasks;
using Jellyfin.Plugin.AlexaSkill.Alexa;
using Jellyfin.Plugin.AlexaSkill.Configuration;
using MediaBrowser.Controller.Library;
using MediaBrowser.Controller.MediaEncoding;
using MediaBrowser.Model.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Jellyfin.Plugin.AlexaSkill.Controller;

/// <summary>
/// Controller that combines album art and audio into a streamable MP4 video
/// for Alexa Echo Show VideoApp playback. Uses ffmpeg to mux a static image
/// with the audio track on-the-fly with chunked streaming.
/// Results are cached so subsequent plays of the same item (with same album art)
/// are served instantly without re-encoding.
/// </summary>
[ApiController]
[Route("alexaskill/api/video-audio")]
public class VideoAudioController : ControllerBase
{
    private readonly ILibraryManager _libraryManager;
    private readonly IMediaEncoder _mediaEncoder;
    private readonly VideoAudioCache _cache;
    private readonly ILogger<VideoAudioController> _logger;

    /// <summary>
    /// Initializes a new instance of the <see cref="VideoAudioController"/> class.
    /// </summary>
    /// <param name="libraryManager">Instance of the <see cref="ILibraryManager"/> interface.</param>
    /// <param name="mediaEncoder">Instance of the <see cref="IMediaEncoder"/> interface.</param>
    /// <param name="cache">Instance of the <see cref="VideoAudioCache"/> service.</param>
    /// <param name="loggerFactory">Instance of the <see cref="ILoggerFactory"/> interface.</param>
    public VideoAudioController(
        ILibraryManager libraryManager,
        IMediaEncoder mediaEncoder,
        VideoAudioCache cache,
        ILoggerFactory loggerFactory)
    {
        _libraryManager = libraryManager;
        _mediaEncoder = mediaEncoder;
        _cache = cache;
        _logger = loggerFactory.CreateLogger<VideoAudioController>();
    }

    /// <summary>
    /// Gets or sets the path to the ffmpeg binary.
    /// Resolved from Jellyfin's <see cref="IMediaEncoder"/> service.
    /// Overridden in tests to inject a mock path.
    /// </summary>
    internal string FfmpegPath { get; set; } = string.Empty;

    /// <summary>
    /// Stream an MP4 video combining album art and audio for the given item.
    /// If a cached version exists (same item + same album art), serves it directly.
    /// Otherwise, generates on-the-fly via ffmpeg and caches the result.
    /// </summary>
    /// <param name="itemId">The Jellyfin audio item ID.</param>
    /// <returns>An MP4 video file.</returns>
    [HttpGet("{itemId}")]
    [AllowAnonymous]
    public async Task<ActionResult> StreamVideoAudio([FromRoute] string itemId)
    {
        var validation = ValidateVideoAudioRequest(itemId);
        if (validation.Error != null)
        {
            return validation.Error;
        }

        // Determine cache key: itemId + album art modification time
        long artModifiedTicks = GetArtModifiedTicks(validation.Item);

        // Check cache first (fast path — no lock needed)
        FileInfo? cached = await _cache.GetCachedFile(itemId, artModifiedTicks).ConfigureAwait(false);
        if (cached != null)
        {
            _logger.LogDebug("VideoAudio: serving cached file for item {ItemId}", itemId);
            return PhysicalFile(cached.FullName, "video/mp4", enableRangeProcessing: true);
        }

        // Cache miss — acquire per-item lock to prevent concurrent ffmpeg processes
        // for the same item. Different items proceed in parallel.
        using (await _cache.LockItemAsync(itemId, artModifiedTicks).ConfigureAwait(false))
        {
            // Clean up any corrupt stub from a previous failed generation.
            // Safe to delete here because we hold the per-item lock.
            _cache.DeleteStubIfPresent(itemId, artModifiedTicks);

            // Double-check cache: another request may have generated the file
            // while we were waiting for the lock
            cached = await _cache.GetCachedFile(itemId, artModifiedTicks).ConfigureAwait(false);
            if (cached != null)
            {
                _logger.LogDebug("VideoAudio: serving file generated by concurrent request for item {ItemId}", itemId);
                return PhysicalFile(cached.FullName, "video/mp4", enableRangeProcessing: true);
            }

            // Build audio URL (ffmpeg fetches it directly via HTTP).
            // Jellyfin's /Audio/{id}/stream endpoint works without auth for static streams.
            string audioUrl = $"{validation.ServerUrl}/Audio/{itemId}/stream?static=true";

            // Determine album art URL — prefer item image, then parent, then black frame.
            // Image endpoints also work without auth.
            string? artUrl = ResolveArtUrl(validation.Item, validation.ServerUrl);
            bool useBlackFrame = artUrl == null;

            _logger.LogDebug(
                "VideoAudio: itemId={ItemId}, artUrl={ArtUrl}, useBlackFrame={UseBlackFrame}",
                itemId,
                artUrl ?? "(black frame)",
                useBlackFrame);

            // Prepare cache file path
            string cachePath = _cache.GetCacheFilePath(itemId, artModifiedTicks);
            string? cacheDir = Path.GetDirectoryName(cachePath);
            if (cacheDir != null)
            {
                Directory.CreateDirectory(cacheDir);
            }

            // Build ffmpeg arguments (includes output file path directly)
            var ffmpegArgs = BuildFfmpegArguments(artUrl, audioUrl, useBlackFrame, cachePath);
            if (_logger.IsEnabled(LogLevel.Debug))
            {
                _logger.LogDebug("VideoAudio: ffmpeg arguments: {Args}", string.Join(" ", ffmpegArgs));
            }

            // Stream-while-writing: start ffmpeg, open the output file for reading
            // while ffmpeg writes, and return a FileStreamResult immediately.
            // The client receives data as ffmpeg produces it instead of waiting
            // for the entire file to be generated first.
#pragma warning disable CA3003 // cachePath is built from GUID-validated itemId and numeric ticks
            var ffmpegProcess = StartFfmpegProcess(validation.FfmpegPath, ffmpegArgs);

            try
            {
                // Wait for ffmpeg to create the output file (it opens the file on startup).
                // This is nearly instantaneous in practice but guards against the race
                // between process.Start() and the file appearing on disk.
                // Also check if ffmpeg has already exited (e.g. invalid input) to avoid
                // a 1-second spin-wait when the process fails fast.
                bool fileAppeared = false;
                for (int i = 0; i < 100; i++)
                {
                    if (System.IO.File.Exists(cachePath))
                    {
                        fileAppeared = true;
                        break;
                    }

                    if (ffmpegProcess.HasExited)
                    {
                        break;
                    }

                    await Task.Delay(10).ConfigureAwait(false);
                }

                if (!fileAppeared)
                {
                    _logger.LogWarning("VideoAudio: ffmpeg failed to create output for item {ItemId} (exit code {ExitCode})", itemId, ffmpegProcess.ExitCode);
                    ffmpegProcess.Dispose();
                    return StatusCode(500, new { error = "Video generation failed" });
                }

                var stream = new FileStream(
                    cachePath,
                    new FileStreamOptions
                    {
                        Mode = FileMode.Open,
                        Access = FileAccess.Read,
                        Share = FileShare.ReadWrite | FileShare.Delete,
                        Options = FileOptions.Asynchronous | FileOptions.SequentialScan
                    });

                // Kill ffmpeg if the client disconnects mid-stream
                HttpContext.RequestAborted.Register(static state =>
                {
                    var proc = (Process)state!;
                    try { proc.Kill(); }
                    catch { /* already exited */ }
                }, ffmpegProcess);

                // Monitor ffmpeg completion in the background: trigger remux + cleanup
                // FileStreamResult owns the stream lifetime — monitor must NOT dispose it.
                _ = MonitorFfmpegAndRemuxAsync(ffmpegProcess, validation.FfmpegPath, cachePath, itemId, artModifiedTicks);
#pragma warning restore CA3003

                _logger.LogDebug("VideoAudio: streaming generated file for item {ItemId}", itemId);
                return new FileStreamResult(stream, "video/mp4");
            }
            catch
            {
                // FileStream creation failed — kill and clean up the ffmpeg process
                try { ffmpegProcess.Kill(); } catch { /* already exited */ }
                ffmpegProcess.Dispose();
                throw;
            }
        }
    }

    /// <summary>
    /// Stream an HLS playlist combining album art and audio for the given item.
    /// HLS provides native seek support and correct duration display on Echo Show from first play.
    /// If a cached HLS directory exists (same item + same album art), serves the playlist directly.
    /// Otherwise, generates HLS segments via ffmpeg, waits for completion, then serves the
    /// complete playlist. Unlike the MP4 endpoint, the playlist must be complete before serving
    /// so the HLS client sees all segments and the correct total duration.
    /// </summary>
    /// <param name="itemId">The Jellyfin audio item ID.</param>
    /// <returns>An HLS playlist (.m3u8) file.</returns>
    [HttpGet("{itemId}/stream.m3u8")]
    [AllowAnonymous]
    public async Task<ActionResult> StreamHlsVideoAudio([FromRoute] string itemId)
    {
        var validation = ValidateVideoAudioRequest(itemId);
        if (validation.Error != null)
        {
            return validation.Error;
        }

        long artModifiedTicks = GetArtModifiedTicks(validation.Item);

        // Check cache first (fast path — no lock needed)
        FileInfo? cached = await _cache.GetCachedHlsPlaylist(itemId, artModifiedTicks).ConfigureAwait(false);
        if (cached != null)
        {
            _logger.LogDebug("VideoAudio HLS: serving cached playlist for item {ItemId}", itemId);
#pragma warning disable CA3003 // path derived from GUID-validated itemId
            return PhysicalFile(cached.FullName, "application/vnd.apple.mpegurl");
#pragma warning restore CA3003
        }

        // Cache miss — acquire per-item lock
        using (await _cache.LockItemAsync(itemId, artModifiedTicks).ConfigureAwait(false))
        {
            // Clean up any corrupt/partial HLS directory from a previous failed generation
            _cache.CleanupHlsStub(itemId, artModifiedTicks);

            // Double-check cache after acquiring lock
            cached = await _cache.GetCachedHlsPlaylist(itemId, artModifiedTicks).ConfigureAwait(false);
            if (cached != null)
            {
                _logger.LogDebug("VideoAudio HLS: serving playlist generated by concurrent request for item {ItemId}", itemId);
#pragma warning disable CA3003
                return PhysicalFile(cached.FullName, "application/vnd.apple.mpegurl");
#pragma warning restore CA3003
            }

            string audioUrl = $"{validation.ServerUrl}/Audio/{itemId}/stream?static=true";
            string? artUrl = ResolveArtUrl(validation.Item, validation.ServerUrl);
            bool useBlackFrame = artUrl == null;

            _logger.LogDebug(
                "VideoAudio HLS: itemId={ItemId}, artUrl={ArtUrl}, useBlackFrame={UseBlackFrame}",
                itemId,
                artUrl ?? "(black frame)",
                useBlackFrame);

#pragma warning disable CA3003 // paths derived from GUID-validated itemId
            string hlsDir = _cache.GetHlsDirectoryPath(itemId, artModifiedTicks);
            Directory.CreateDirectory(hlsDir);

            string playlistPath = Path.Combine(hlsDir, "stream.m3u8");
            string segmentPath = Path.Combine(hlsDir, "seg_%03d.ts");
            string hlsBaseUrl = $"/alexaskill/api/video-audio/{itemId}/segments/";

            var ffmpegArgs = BuildHlsFfmpegArguments(artUrl, audioUrl, useBlackFrame, playlistPath, segmentPath, hlsBaseUrl);
            if (_logger.IsEnabled(LogLevel.Debug))
            {
                _logger.LogDebug("VideoAudio HLS: ffmpeg arguments: {Args}", string.Join(" ", ffmpegArgs));
            }

            // Generate HLS: wait for ffmpeg to complete so the playlist has all segments
            // and the Echo Show sees the correct total duration from the first request.
            using var cts = new CancellationTokenSource(TimeSpan.FromMinutes(5));

            try
            {
                await RunFfmpegToCompletionAsync(validation.FfmpegPath, ffmpegArgs, cts.Token).ConfigureAwait(false);

                // Register the HLS directory for fast segment lookups (avoids filesystem scan per segment)
                _cache.RegisterHlsDirectory(itemId, artModifiedTicks);

                // Background eviction — don't block the response
                _ = Task.Run(() => _cache.EvictIfNeeded(), CancellationToken.None);

                _logger.LogDebug("VideoAudio HLS: serving generated playlist for item {ItemId}", itemId);
                return PhysicalFile(playlistPath, "application/vnd.apple.mpegurl");
            }
            catch (OperationCanceledException)
            {
                _logger.LogWarning("VideoAudio HLS: ffmpeg timed out for item {ItemId}", itemId);
                return StatusCode(504, new { error = "HLS generation timed out" });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "VideoAudio HLS: ffmpeg failed for item {ItemId}", itemId);
                return StatusCode(500, new { error = "HLS generation failed" });
            }
#pragma warning restore CA3003
        }
    }

    /// <summary>
    /// Serve an individual HLS segment (.ts) file for a given item.
    /// The segment name is validated against a strict pattern (seg_NNN.ts) to prevent
    /// directory traversal attacks. The segment directory is resolved via the cache service.
    /// </summary>
    /// <param name="itemId">The Jellyfin audio item ID.</param>
    /// <param name="segmentName">The segment file name (e.g. "seg_000.ts").</param>
    /// <returns>The segment file.</returns>
    [HttpGet("{itemId}/segments/{segmentName}")]
    [AllowAnonymous]
    public ActionResult GetSegment([FromRoute] string itemId, [FromRoute] string segmentName)
    {
        if (string.IsNullOrWhiteSpace(itemId) || !Guid.TryParse(itemId, out _))
        {
            return BadRequest(new { error = "Invalid itemId format" });
        }

        // Validate segment name to prevent directory traversal
        if (!VideoAudioCache.IsValidSegmentName(segmentName))
        {
            _logger.LogWarning("VideoAudio: rejected invalid segment name '{SegmentName}' for item {ItemId}", segmentName, itemId);
            return BadRequest(new { error = "Invalid segment name" });
        }

        string? segmentPath = _cache.FindSegmentPath(itemId, segmentName);
        if (segmentPath == null)
        {
            return NotFound(new { error = "Segment not found" });
        }

#pragma warning disable CA3003 // segmentPath validated via GUID itemId + strict segment name pattern
        return PhysicalFile(segmentPath, "video/mp2t", enableRangeProcessing: true);
#pragma warning restore CA3003
    }

    /// <summary>
    /// Validate a video-audio request: parse itemId, resolve ffmpeg, look up the item,
    /// check it's a streamable media type, and verify plugin configuration.
    /// Shared by both MP4 and HLS endpoints to avoid duplicating validation logic.
    /// </summary>
    /// <param name="itemId">The raw itemId string from the route.</param>
    /// <returns>A validated result, or a result with <see cref="ValidatedRequest.Error"/> set.</returns>
    private ValidatedRequest ValidateVideoAudioRequest(string itemId)
    {
        if (string.IsNullOrWhiteSpace(itemId) || !Guid.TryParse(itemId, out Guid itemGuid))
        {
            return new ValidatedRequest { Error = BadRequest(new { error = "Invalid itemId format" }) };
        }

        string ffmpeg = ResolveFfmpegPath();
        if (string.IsNullOrEmpty(ffmpeg))
        {
            _logger.LogError("ffmpeg not available for VideoAudio request");
            return new ValidatedRequest { Error = StatusCode(503, new { error = "ffmpeg is not available on this server" }) };
        }

        MediaBrowser.Controller.Entities.BaseItem? item = _libraryManager.GetItemById(itemGuid);
        if (item == null)
        {
            _logger.LogWarning("VideoAudio: item {ItemId} not found", itemId);
            return new ValidatedRequest { Error = NotFound(new { error = "Item not found" }) };
        }

        if (item is not MediaBrowser.Controller.Entities.IHasMediaSources)
        {
            _logger.LogWarning("VideoAudio: item {ItemId} ({ItemType}) is not a streamable media type", itemId, item.GetType().Name);
            return new ValidatedRequest { Error = BadRequest(new { error = "Item is not a streamable media type" }) };
        }

        var config = Plugin.Instance?.Configuration;
        if (config == null || string.IsNullOrWhiteSpace(config.ServerAddress))
        {
            return new ValidatedRequest { Error = StatusCode(503, new { error = "Plugin not configured" }) };
        }

        return new ValidatedRequest
        {
            FfmpegPath = ffmpeg,
            Item = item,
            ServerUrl = config.ServerAddress.TrimEnd('/')
        };
    }

    /// <summary>
    /// Holds the result of <see cref="ValidateVideoAudioRequest"/>. If validation passes,
    /// <see cref="Error"/> is null and the other fields are populated.
    /// </summary>
    private sealed class ValidatedRequest
    {
        public ActionResult? Error { get; set; }
        public string FfmpegPath { get; set; } = string.Empty;
        public MediaBrowser.Controller.Entities.BaseItem Item { get; set; } = null!;
        public string ServerUrl { get; set; } = string.Empty;
    }

    /// <summary>
    /// Run ffmpeg to completion: start the process, await exit with a cancellation token,
    /// and throw on non-zero exit code. Used by HLS generation (which needs the complete
    /// output before serving) and by the faststart remux.
    /// </summary>
    /// <param name="ffmpegPath">Path to ffmpeg binary.</param>
    /// <param name="arguments">ffmpeg command-line arguments as individual tokens.</param>
    /// <param name="cancellationToken">Cancellation token for timeout/abort.</param>
    private async Task RunFfmpegToCompletionAsync(
        string ffmpegPath,
        List<string> arguments,
        CancellationToken cancellationToken)
    {
        using var process = StartFfmpegProcess(ffmpegPath, arguments);

        await process.WaitForExitAsync(cancellationToken).ConfigureAwait(false);

        if (process.ExitCode != 0)
        {
            _logger.LogWarning("ffmpeg exited with code {ExitCode}", process.ExitCode);
            throw new InvalidOperationException($"ffmpeg exited with code {process.ExitCode}");
        }
    }

    /// <summary>
    /// Resolve the album art URL for the given item. Returns null if no suitable image is available.
    /// Priority: item's own Primary image > parent (album) Primary image > parent ID fallback > null.
    /// </summary>
    /// <param name="item">The Jellyfin audio item.</param>
    /// <param name="serverUrl">The base server URL (no trailing slash).</param>
    /// <returns>Art URL string or null.</returns>
    internal static string? ResolveArtUrl(
        MediaBrowser.Controller.Entities.BaseItem item,
        string serverUrl)
    {
        // Check if the item itself has a primary image
        if (item.HasImage(ImageType.Primary, 0))
        {
            return $"{serverUrl}/Items/{item.Id}/Images/Primary";
        }

        // For audio items, try to find the album parent's primary image
        if (item is MediaBrowser.Controller.Entities.Audio.Audio)
        {
            var album = item.FindParent<MediaBrowser.Controller.Entities.Audio.MusicAlbum>();
            if (album != null && album.HasImage(ImageType.Primary, 0))
            {
                return $"{serverUrl}/Items/{album.Id}/Images/Primary";
            }
        }

        // No suitable image found — fall back to black frame
        return null;
    }

    /// <summary>
    /// Build ffmpeg argument list for combining album art + audio into MP4.
    /// Returns individual arguments for use with <see cref="ProcessStartInfo.ArgumentList"/>,
    /// which passes each token directly to the OS — no shell interpretation, no injection risk.
    /// </summary>
    /// <param name="artUrl">Album art URL (null for black frame fallback).</param>
    /// <param name="audioUrl">Audio stream URL.</param>
    /// <param name="useBlackFrame">Whether to generate a black frame instead of using art.</param>
    /// <param name="outputPath">File path for the output MP4.</param>
    /// <returns>List of ffmpeg arguments (one token per entry).</returns>
    internal static List<string> BuildFfmpegArguments(string? artUrl, string audioUrl, bool useBlackFrame, string outputPath)
    {
        var args = new List<string>();

        if (useBlackFrame)
        {
            args.AddRange(BlackFrameInputArgs);
        }
        else
        {
            args.AddRange(ArtInputPrefixArgs);
            args.Add(artUrl!);
        }

        args.Add("-i");
        args.Add(audioUrl);
        args.AddRange(VideoCodecArgs);
        args.AddRange(AudioCodecArgs);
        args.AddRange(PixelFormatArgs);
        args.AddRange(VideoFilterArgs);
        args.AddRange(OutputFormatArgs);
        args.Add("-shortest");
        args.Add(outputPath);

        return args;
    }

    private static readonly string[] BlackFrameInputArgs = ["-f", "lavfi", "-i", "color=c=black:s=1280x720:d=999"];
    private static readonly string[] ArtInputPrefixArgs = ["-loop", "1", "-framerate", "1", "-i"];
    private static readonly string[] VideoCodecArgs = ["-c:v", "libx264", "-tune", "stillimage", "-preset", "ultrafast", "-crf", "28"];
    private static readonly string[] AudioCodecArgs = ["-c:a", "aac", "-b:a", "128k"];
    private static readonly string[] PixelFormatArgs = ["-pix_fmt", "yuv420p", "-r", "1"];
    private static readonly string[] VideoFilterArgs = ["-vf", "scale=1280x720:force_original_aspect_ratio=decrease,pad=1280:720:(ow-iw)/2:(oh-ih)/2:black"];
    private static readonly string[] OutputFormatArgs = ["-f", "mp4", "-movflags", "frag_keyframe+empty_moov"];
    private static readonly string[] FaststartRemuxArgs = ["-f", "mp4", "-movflags", "+faststart"];

    /// <summary>
    /// Build ffmpeg argument list for generating HLS output (playlist + segments).
    /// Returns individual arguments for use with <see cref="ProcessStartInfo.ArgumentList"/>.
    /// HLS provides native seek support and correct duration display on Echo Show from first play.
    /// </summary>
    /// <param name="artUrl">Album art URL (null for black frame fallback).</param>
    /// <param name="audioUrl">Audio stream URL.</param>
    /// <param name="useBlackFrame">Whether to generate a black frame instead of using art.</param>
    /// <param name="playlistPath">File path for the output .m3u8 playlist.</param>
    /// <param name="segmentPath">File path template for segments (e.g. dir/seg_%03d.ts).</param>
    /// <param name="hlsBaseUrl">Base URL prefix for segment URLs in the playlist.</param>
    /// <returns>List of ffmpeg arguments (one token per entry).</returns>
    internal static List<string> BuildHlsFfmpegArguments(
        string? artUrl,
        string audioUrl,
        bool useBlackFrame,
        string playlistPath,
        string segmentPath,
        string hlsBaseUrl)
    {
        var args = new List<string>();

        // Input: album art (looped) or black frame
        if (useBlackFrame)
        {
            args.AddRange(BlackFrameInputArgs);
        }
        else
        {
            args.AddRange(ArtInputPrefixArgs);
            args.Add(artUrl!);
        }

        args.Add("-i");
        args.Add(audioUrl);

        // Video codec
        args.AddRange(VideoCodecArgs);

        // Audio codec
        args.AddRange(AudioCodecArgs);

        // Pixel format + frame rate
        args.AddRange(PixelFormatArgs);

        // Video filter (scale + pad)
        args.AddRange(VideoFilterArgs);

        // HLS-specific flags
        args.Add("-hls_time");
        args.Add("4");
        args.Add("-hls_list_size");
        args.Add("0");
        args.Add("-hls_flags");
        args.Add("append_list+delete_segments+omit_endlist");

        // Segment file name template
        args.Add("-hls_segment_filename");
        args.Add(segmentPath);

        // Base URL for segment references in the playlist
        args.Add("-hls_base_url");
        args.Add(hlsBaseUrl);

        args.Add("-shortest");
        args.Add(playlistPath);

        return args;
    }

    /// <summary>
    /// Get the album art DateModified ticks for use as a cache key component.
    /// When album art changes, the cache key changes and the old entry becomes stale.
    /// </summary>
    /// <param name="item">The Jellyfin item.</param>
    /// <returns>DateModified ticks from the primary image, or 0 if no image.</returns>
    internal static long GetArtModifiedTicks(MediaBrowser.Controller.Entities.BaseItem item)
    {
        var imageInfo = item.GetImageInfo(ImageType.Primary, 0);
        if (imageInfo != null && imageInfo.DateModified != default)
        {
            return imageInfo.DateModified.Ticks;
        }

        // For audio items, try album parent's image
        if (item is MediaBrowser.Controller.Entities.Audio.Audio)
        {
            var album = item.FindParent<MediaBrowser.Controller.Entities.Audio.MusicAlbum>();
            if (album != null)
            {
                var albumImageInfo = album.GetImageInfo(ImageType.Primary, 0);
                if (albumImageInfo != null && albumImageInfo.DateModified != default)
                {
                    return albumImageInfo.DateModified.Ticks;
                }
            }
        }

        return 0;
    }

    /// <summary>
    /// Resolve the path to the ffmpeg binary.
    /// Tries IMediaEncoder first, then falls back to PATH lookup.
    /// </summary>
    /// <returns>Path to ffmpeg or empty string if not found.</returns>
    private string ResolveFfmpegPath()
    {
        if (!string.IsNullOrEmpty(FfmpegPath))
        {
            return FfmpegPath;
        }

        try
        {
            string? encoderPath = _mediaEncoder.EncoderPath;
            if (!string.IsNullOrEmpty(encoderPath) && System.IO.File.Exists(encoderPath))
            {
                return encoderPath;
            }
        }
        catch (Exception ex)
        {
            _logger.LogDebug(ex, "Could not resolve ffmpeg path from IMediaEncoder");
        }

        // Fallback: try to find ffmpeg on PATH
        try
        {
            string? pathEnv = Environment.GetEnvironmentVariable("PATH");
            if (!string.IsNullOrEmpty(pathEnv))
            {
                string ffmpegName = RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ? "ffmpeg.exe" : "ffmpeg";
                foreach (string dir in pathEnv.Split(Path.PathSeparator, StringSplitOptions.RemoveEmptyEntries))
                {
                    string candidate = Path.Combine(dir, ffmpegName);
                    if (System.IO.File.Exists(candidate))
                    {
                        return candidate;
                    }
                }
            }
        }
        catch (Exception ex)
        {
            _logger.LogDebug(ex, "Error searching PATH for ffmpeg");
        }

        return string.Empty;
    }

    /// <summary>
    /// Start an ffmpeg process writing to disk without awaiting its completion.
    /// Used by the stream-while-writing path so the response can start sending
    /// data while ffmpeg is still producing output.
    /// The caller is responsible for awaiting <see cref="Process.WaitForExitAsync"/>
    /// and disposing the process.
    /// </summary>
    /// <param name="ffmpegPath">Path to ffmpeg binary.</param>
    /// <param name="arguments">ffmpeg command-line arguments as individual tokens.</param>
    /// <returns>The started ffmpeg <see cref="Process"/> (not yet awaited).</returns>
    private Process StartFfmpegProcess(string ffmpegPath, List<string> arguments)
    {
        var process = new Process();
        process.StartInfo = new ProcessStartInfo
        {
            FileName = ffmpegPath,
            UseShellExecute = false,
            CreateNoWindow = true,
            RedirectStandardOutput = false,
            RedirectStandardError = true
        };

        foreach (string arg in arguments)
        {
            process.StartInfo.ArgumentList.Add(arg);
        }

        process.Start();

        // Drain stderr asynchronously to prevent deadlock
        _ = Task.Run(async () =>
        {
            using var reader = process.StandardError;
            string? line;
            while ((line = await reader.ReadLineAsync().ConfigureAwait(false)) != null)
            {
                _logger.LogDebug("ffmpeg stderr: {Line}", line);
            }
        });

        return process;
    }

    /// <summary>
    /// Monitor an ffmpeg process that was started by <see cref="StartFfmpegProcess"/>.
    /// Waits for the process to exit (with a 5-minute timeout), then triggers the
    /// background faststart remux. Disposes the process when done.
    /// The read stream is NOT disposed here — <see cref="FileStreamResult"/> owns it.
    /// </summary>
    /// <param name="process">The ffmpeg process (started, not yet awaited).</param>
    /// <param name="ffmpegPath">Path to ffmpeg binary (for remux).</param>
    /// <param name="cachePath">Path to the fragmented MP4 cache file.</param>
    /// <param name="itemId">Item ID for remux path computation.</param>
    /// <param name="artModifiedTicks">Art ticks for remux path computation.</param>
    /// <returns>A task representing the background monitoring operation.</returns>
    private async Task MonitorFfmpegAndRemuxAsync(
        Process process,
        string ffmpegPath,
        string cachePath,
        string itemId,
        long artModifiedTicks)
    {
        try
        {
            using var timeoutCts = new CancellationTokenSource(TimeSpan.FromMinutes(5));
            await process.WaitForExitAsync(timeoutCts.Token).ConfigureAwait(false);

            if (process.ExitCode != 0)
            {
                _logger.LogWarning("ffmpeg exited with code {ExitCode} for item {ItemId}", process.ExitCode, itemId);
            }
            else
            {
                // Background: remux to a separate .fs.mp4 file with +faststart for seeking.
                // Writes to a NEW file — never overwrites the fragmented version.
                // Next play will prefer the seekable version via GetCachedFile.
                _ = RemuxToFaststartAsync(ffmpegPath, cachePath, itemId, artModifiedTicks);

                // Background eviction — don't block
                _ = Task.Run(() => _cache.EvictIfNeeded(), CancellationToken.None);
            }
        }
        catch (OperationCanceledException)
        {
            _logger.LogWarning("ffmpeg timed out (5 min) for item {ItemId}", itemId);
            try { process.Kill(); } catch { /* already exited */ }
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "ffmpeg monitoring failed for item {ItemId}", itemId);
        }
        finally
        {
            process.Dispose();
        }
    }

    /// <summary>
    /// Background task: remux the fragmented MP4 to a separate seekable faststart file.
    /// Writes to <c>.fs.mp4</c> — a completely independent file that never overwrites the
    /// fragmented original. On next play, <see cref="VideoAudioCache.GetCachedFile"/> prefers
    /// the faststart version. Uses stream copy (-c copy) — no re-encoding, only I/O bound.
    /// </summary>
    /// <param name="ffmpegPath">Path to ffmpeg binary.</param>
    /// <param name="fragmentedPath">Path to the fragmented MP4 (input).</param>
    /// <param name="itemId">Item ID for computing the faststart output path.</param>
    /// <param name="artModifiedTicks">Art ticks for computing the faststart output path.</param>
    /// <returns>A task representing the background remux operation.</returns>
    private async Task RemuxToFaststartAsync(string ffmpegPath, string fragmentedPath, string itemId, long artModifiedTicks)
    {
        string faststartPath = _cache.GetFaststartCacheFilePath(itemId, artModifiedTicks);

        // Already have a faststart version? Skip.
#pragma warning disable CA3003
        if (System.IO.File.Exists(faststartPath))
#pragma warning restore CA3003
        {
            return;
        }

        try
        {
            var remuxArgs = new List<string> { "-i", fragmentedPath, "-c", "copy" };
            remuxArgs.AddRange(FaststartRemuxArgs);
            remuxArgs.Add(faststartPath);

            using var process = StartFfmpegProcess(ffmpegPath, remuxArgs);

            await process.WaitForExitAsync().ConfigureAwait(false);

            if (process.ExitCode != 0)
            {
                _logger.LogWarning("ffmpeg remux exited with code {ExitCode}", process.ExitCode);
#pragma warning disable CA3003
                TryDelete(faststartPath);
#pragma warning restore CA3003
                return;
            }

            _logger.LogDebug("VideoAudio: remuxed to faststart: {Path}", faststartPath);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "VideoAudio: faststart remux failed for {Path}", fragmentedPath);
        }
    }

#pragma warning disable CA3003 // path derived from cachePath built from GUID-validated itemId
    private static void TryDelete(string path)
    {
        try
        {
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }
        }
        catch (IOException)
        {
            // Best effort
        }
    }
#pragma warning restore CA3003
}
