using System;
using global::Alexa.NET.Request;
using global::Alexa.NET.Request.Type;
using global::Alexa.NET.Response;
using Jellyfin.Plugin.AlexaSkill.Alexa.Handler;
using AlexaSession = global::Alexa.NET.Request.Session;

namespace Jellyfin.Plugin.AlexaSkill.Alexa.Pipeline;

/// <summary>
/// Context object passed through the interceptor pipeline.
/// </summary>
public class RequestContext
{
    /// <summary>
    /// Initializes a new instance of the <see cref="RequestContext"/> class.
    /// </summary>
    /// <param name="skillRequest">The Alexa skill request.</param>
    /// <param name="alexaContext">The Alexa context.</param>
    /// <param name="alexaSession">The Alexa session.</param>
    /// <param name="handler">The handler selected to process this request.</param>
    public RequestContext(Request skillRequest, Context alexaContext, AlexaSession? alexaSession, BaseHandler handler)
    {
        SkillRequest = skillRequest;
        AlexaContext = alexaContext;
        AlexaSession = alexaSession;
        Handler = handler;
    }

    /// <summary>
    /// Gets the Alexa skill request being processed.
    /// </summary>
    public Request SkillRequest { get; }

    /// <summary>
    /// Gets the Alexa context (device info, API tokens).
    /// </summary>
    public Context AlexaContext { get; }

    /// <summary>
    /// Gets the Alexa session (session attributes, new session flag).
    /// </summary>
    public AlexaSession? AlexaSession { get; }

    /// <summary>
    /// Gets the handler selected to process this request.
    /// </summary>
    public BaseHandler Handler { get; }

    /// <summary>
    /// Gets or sets the skill response generated by the handler or interceptors.
    /// </summary>
    public SkillResponse? Response { get; set; }

    /// <summary>
    /// Gets the request type string for logging/metrics.
    /// </summary>
    public string RequestType => SkillRequest?.Type ?? "unknown";

    /// <summary>
    /// Gets or sets the timestamp when request processing started.
    /// Set by the first request interceptor in the pipeline.
    /// </summary>
    public DateTimeOffset StartedAt { get; set; }
}
